try:
    x = int(input('enter a num: '))
    y = 1/x


finally:
    print('we are not carrying the exception')

print('the value y is:', y)